// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfYavd3M9iQHzKEFMH6bBjWYlAv8X-VNQ',
    appId: '1:139168461688:web:3fe24eeef6dbbb3eae0e8d',
    messagingSenderId: '139168461688',
    projectId: 'practicafinalflutter',
    authDomain: 'practicafinalflutter.firebaseapp.com',
    storageBucket: 'practicafinalflutter.appspot.com',
    measurementId: 'G-3KB1H2JTP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb64bFd-LsnxtZ5bzmT7xplvB7YL5ZpVw',
    appId: '1:139168461688:android:dc071c529edb916aae0e8d',
    messagingSenderId: '139168461688',
    projectId: 'practicafinalflutter',
    storageBucket: 'practicafinalflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxQ4Dp3XARBIkkmxDFZQEsw472BdYjXBY',
    appId: '1:139168461688:ios:8f49fd381546a4e0ae0e8d',
    messagingSenderId: '139168461688',
    projectId: 'practicafinalflutter',
    storageBucket: 'practicafinalflutter.appspot.com',
    iosClientId: '139168461688-b8bpkcs7nh0dk3dpu9s85bp5cqhonl1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabajofinal',
  );
}
